class mainconst:
    class_names = [
        "10_clover",
        "10_diamond",
        "10_heart",
        "10_spade",
        "1_clover",
        "1_diamond",
        "1_heart",
        "1_spade",
        "2_clover",
        "2_diamond",
        "2_heart",
        "2_spade",
        "3_clover",
        "3_diamond",
        "3_heart",
        "3_spade",
        "4_clover",
        "4_diamond",
        "4_heart",
        "4_spade",
        "5_clover",
        "5_diamond",
        "5_heart",
        "5_spade",
        "6_clover",
        "6_diamond",
        "6_heart",
        "6_spade",
        "7_clover",
        "7_diamond",
        "7_heart",
        "7_spade",
        "8_clover",
        "8_diamond",
        "8_heart",
        "8_spade",
        "9_clover",
        "9_diamond",
        "9_heart",
        "9_spade",
        "J_clover",
        "J_diamond",
        "J_heart",
        "J_spade",
        "K_clover",
        "K_diamond",
        "K_heart",
        "K_spade",
        "Q_clover",
        "Q_diamond",
        "Q_heart",
        "Q_spade",
    ]
    window_title = "MEmu"  # エミュレータのウィンドウタイトル
    card_region_1st = (260, 975, 380, 1125)  # カードが表示されるエリアを調整
    card_region_2nd = (380, 975, 500, 1125)  # カードが表示されるエリアを調整

    # スクショ保存するパス設定

    screenshot_save_path = r"D:\develop\poker\screenshot"
